config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'

  get '/tasks', to: 'tasks#index'
  get '/task/new', to: 'tasks#new', as: :new
  post '/tasks', to: 'tasks#create'
  get '/task/:id/edit', to: 'tasks#edit', as: :edit
  patch '/task/:id', to: 'tasks#update'

  delete "task/:id", to: "tasks#destroy"

  get '/task/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @new_task = Task.new(task_params)
    @new_task.save

    redirect_to root_path(@new_task.id)
  end

  def edit #mostrare form
    @task = Task.find(params[:id])
  end

  def update #patch request
     @task = Task.find(params[:id])
     @task.update(task_params)

     redirect_to root_path(@task.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to :root
  end


  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1 class="title">Update your task</h1>

    <div class="task-card">
      <%= form_for(@task) do |f| %>
      <%= f.label :title, class: "label" %>
      <%= f.text_field :title, class: "input"%>
      <%= f.label :details, class: "label" %>
      <%= f.text_field :details, class: "input"%>
      <%= f.label :completed, class: "label" %>
      <%= f.check_box :completed %>
      <%= f.submit "update", class: "btn"%>
      <% end %>
    </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class="title">Task list</h1>

  <ol id='class-list'>
    <% @tasks.each do |task| %>
    <div class="task-card">
      <li class="task link"><%= link_to task.title, task_path(task.id) ,class: "link"%></li>
      <%= form_for(task) do |f| %>
      <%= f.label :done?, class: "label" %>
      <%=f.check_box :completed %>
      <%= f.submit "mark as done", class: "btn-small" %>
      <% end %>
    </div>
    <% end %>
  </ol>
  <%= link_to 'create a new Task', new_path, class: "btn link" %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1 class="title">Create a new task</h1>

    <div class="task-card">
      <%= form_for(@task) do |f| %>
      <%= f.label :title, class: "label" %>
      <%= f.text_field :title, class: "input"%>
      <%= f.label :details, class: "label"%>
      <%= f.text_field :details, class: "input"%>
      <%= f.label :completed, class: "label"%>
      <%= f.check_box :completed %>
      <%= f.submit "create task", class: "btn"%>
      <% end %>
    </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1 class="title">Details</h1>
  <h3><%= @task.details %></h3>

  <%= link_to 'back to the list', root_path, class: "btn link" %>

  <%= link_to 'edit this task', edit_path, class: "btn link" %>

  <!-- prima vai all action destroy (nel method , una volta eseguito redirect al root) -->
  <%= link_to 'destroy', task_path(@task), method: :delete, data: { confirm: "Are you sure?" }, class: "btn link" %>
</div>